In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 245.8 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 262.6 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 191.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 1.6 MB/s eta 0:00:10
   ---------------------------------------- 0.1/15.8 MB 1.1 MB/s eta 0:00:15
   ---------------------------------------- 0.2/15.8 MB 1.7 MB/s eta 0:00:10
    --------------------------------------- 0.3/15.8 MB 1.5 MB/s eta 0:00:11
    --------------------------------------- 0.3/15.8 MB 1.7 MB/s eta 0:00:10


In [3]:
import numpy as np

In [56]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [57]:
array_a = np.array([1,2,3,4])

In [58]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [59]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [60]:
array_a[0]

1

In [61]:
array_b[-1]

2.0

In [62]:
array_a[:2]

array([1, 2])

dtype ----> arraydeki datanın tipini verir

In [63]:
array_a.dtype

dtype('int32')

In [64]:
array_b.dtype

dtype('float64')

In [65]:
empty_array = np.array([])

In [66]:
empty_array.dtype             #deffault değer olarak float alır.

dtype('float64')

In [67]:
np.array([1,2,3,4], dtype = np.float_)  #dizinin data tipini belirlemek için

array([1., 2., 3., 4.])

In [68]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [69]:
array_c = np.array(["ada","lovelace"])

In [70]:
array_c.dtype   #stringler Unicode olarak varsayılan olarak işlenir.

dtype('<U8')

### Dimensions and Shapes

shape özelliği, bir dizi üzerinde kullanılarak dizinin boyutlarını veren bir tuple döndürür.


In [71]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [72]:
array_a.shape      #    Bu demet, tek boyutlu bir diziyi temsil eder ve içinde 4 eleman bulunduğunu gösterir

(4,)

In [73]:
my_array.shape   #2 satır 3 sütün

(2, 3)

In [74]:
array_a.ndim    
# ndim özelliği, bir NumPy dizisinin boyut sayısını (dimension) belirten bir özelliktir. Bu özellik, bir dizi kaç boyutlu ise o boyut sayısını verir.

1

In [75]:
my_array.ndim

2

In [76]:
my_array.size  #eleman sayısı

6

In [77]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [78]:
my_array.ndim

3

In [80]:
my_array.shape

'''Bu tuple, my_array dizisinin 2 adet "ana liste" içerdiğini, 
her bir "ana liste"nin 2 adet "alt liste" içerdiğini 
ve her bir "alt liste"nin 3 adet eleman içerdiğini belirtir. 
Yani, bu üç boyutlu bir dizi olduğunu ifade eder.
'''

(2, 2, 3)

In [81]:
my_array.ndim

3

In [88]:
my_array.size

12

In [84]:
xyz = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
        [5,6,7],
        [6, 5, 6],
    ],
    [
        [6, 5, 6],
        [3, 2, 1],
        [2,3,4],
        [5,6,7]
    ]
])

In [85]:
xyz.ndim

3

In [87]:
xyz.shape  #2 adet ana liste,
           #Her ana liste içinde 4 adet alt liste
           #Her alt listenin içinde 3 eleman

(2, 4, 3)

In [89]:
xyz.size

24

indexing and slicing

In [91]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]   
])

In [92]:
my_array[1]       #2. satırını getirir. 0 - 1 - 2 diye numaralandırıldığı için 1 yazılır

array([4, 5, 6])

In [93]:
my_array[1][0]  #2. satır1. eleman

4

In [94]:
my_array[0:2]    # 0 - 1 - 2 satırlarından 0 ve 1 alınır

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [96]:
my_array[1] = np.array([10,10,10])

In [97]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [98]:
my_array[2] = 99

In [99]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [100]:
np.arange(1,10,2)
# arange fonksiyonunu kullanarak 1'den başlayarak 10'a kadar (10 hariç) olan sayıları
# 2'şer 2'şer artırarak içeren bir NumPy dizisi oluşturur.

array([1, 3, 5, 7, 9])

In [101]:
my_array = np.arange(0,10) #arange fonksiyonunu kullanarak 0'dan başlayarak 10'a kadar (10 hariç) olan sayıları içeren bir NumPy dizisi oluşturur.
my_array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
my_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [103]:
np.arange(1, 10.1, 4)  #1'den başlayarak 10.1'e kadar (10.1 hariç) olan sayıları 4'er 4'er artırarak içeren bir NumPy dizisi oluşturur.

array([1., 5., 9.])

In [104]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [105]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [106]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [110]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- .random()    --> float değerde
- .randint()   --->int değerde
random sayı üretme fonksiyonu

In [108]:
my_array = np.random.random((5,2))   #sadece .random(x,y) yazarsak iki değer arasında float değerler alır

In [109]:
my_array

array([[0.58382878, 0.7698826 ],
       [0.68329074, 0.38899422],
       [0.96021016, 0.41160668],
       [0.18745062, 0.17492277],
       [0.46376907, 0.59309787]])

In [4]:
np.random.randint(100, size=(5,5))

array([[22, 42, 40, 48, 55],
       [26, 43, 78, 99, 57],
       [46, 85, 58, 31, 54],
       [32, 23, 73, 76, 29],
       [15, 21, 79, 29, 88]])

### any() ve all() Fonksiyonu:

numpy.any() fonksiyonu, bir dizi içinde herhangi bir elemanın True (doğru) değerine sahip olup olmadığını kontrol eder.
Eğer dizide en az bir True değeri varsa, True döndürür; aksi halde False döndürür.

### full() Fonksiyonu:

numpy.full() fonksiyonu, belirli bir boyutta ve belirli bir değeri içeren bir dizi oluşturur.
Örneğin, numpy.full((shape), fill_value) şeklinde kullanılabilir.

### concatenate() Fonksiyonu:

numpy.concatenate() fonksiyonu, iki veya daha fazla diziyi birleştirmek için kullanılır.
Birleştirmek istediğiniz dizileri ve birleştirme ekseni (axis) parametresini belirtmeniz gereklidir.

In [112]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
array1 = array1.reshape(2, 5)

In [114]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
np.concatenate([array1, array1]) #axis=None (veya axis=0) ile birleştirmede dizilerin satır bazında birleştiril

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
np.concatenate([array1, array1], axis=1) #axis=1 ile birleştirmede ise sütun bazında birleştirildiğini göstermektedir.

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### Statics

In [119]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
array1.sum()

45

In [7]:
array1.mean()  #aritmetik ortalama

4.5

In [8]:
array1.std()  #standart sapma

2.8722813232690143

In [9]:
array1.var()        #varyans

8.25

In [123]:
array1.sum(axis= 0)

array([ 5,  7,  9, 11, 13])

In [121]:
array1.sum(axis=1)

array([10, 35])

In [126]:
array1 + 10

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [129]:
array1 += 10   #çalıştırdıkça artar
array1

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [130]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [131]:
array2 + 10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [132]:
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

boolean arrays

In [17]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [18]:
a[0], a[-1]

(0, 3)

In [19]:
a[[0, -1]]

array([0, 3])

In [20]:
a[[True, False ,False ,True]]

array([0, 3])

In [21]:
a >= 2

array([False, False,  True,  True])

In [22]:
a[a >= 2]

array([2, 3])

In [23]:
a.mean()

1.5

In [26]:
a[a > a.mean()]

array([2, 3])

In [25]:
a[~(a > a.mean())]

array([0, 1])

In [27]:
a[(a ==0) | (a == 1)]

array([0, 1])

In [28]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

- 100e kadar rastgele tam sayılardan oluşan 3,3 bir matris kurun
-  30dan büyük olanları boolean yöntemi ile filtreleyin

In [33]:
rand_arr= np.random.randint(100, size= (3,3))
rand_arr

array([[46, 60, 59],
       [76, 86, 93],
       [80, 68, 24]])

In [34]:
rand_arr[rand_arr>30]

array([46, 60, 59, 76, 86, 93, 80, 68])

In [35]:
boolean_array = rand_arr > 30
boolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [36]:
rand_arr[boolean_array]

array([46, 60, 59, 76, 86, 93, 80, 68])

In [37]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [38]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
np.dot(array_1, array_2)   # iki dizinin iç çarpımı

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [41]:
array_2.T  #transpozunu (transpose) alır. Transpoz, bir matrisin satırlarını sütunlarına ve sütunlarını satırlarına dönüştüren bir işlemdir.

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [42]:
import sys

In [133]:
a=sys.getsizeof(10) #bir nesnenin bellekte kapladığı alanın boyutunu (byte cinsinden) döndüren bir fonksiyondur.
print(a)

28


In [46]:
sys.getsizeof(1000**100)

160

In [47]:
np.dtype(int).itemsize

4

In [135]:
np.dtype(np.int8).itemsize
"""np.int8 veri tipinin bellekte kaç byte yer kapladığını gösterir. 
itemsize, bir veri tipinin bellekte kapladığı byte sayısını döndürür.
Örneğin, np.int8 tipi, 8 bit (bir byte) yer kaplar, bu nedenle itemsize değeri 1 olacaktır."""

1

In [49]:
np.dtype(float).itemsize

8

In [50]:
sys.getsizeof([1,2,3])

88

In [138]:
np.array([1, 2, 3]).nbytes  #HOCAYLA FARKLI SONUÇLAR 

12

In [53]:
my_list = list(range(100000))

In [139]:
my_array = np.arange(100000)

In [141]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [55]:
%time np.sum([number** 2 for number in my_list])

CPU times: total: 46.9 ms
Wall time: 105 ms


333328333350000